version: 2.1

jobs: 
  lint:
    docker:
      - image: cimg/php:8.0-browsers
    steps:
      - checkout
      - run:
          name: Install Composer
          command: |
            curl -s https://getcomposer.org/installer | php
            mv composer.phar /usr/local/bin/composer
      - run:
          name: Install Composer dependencies
          command: composer install
      - run:
          name: Lint PHP 
          command: composer php:lint
  build:
    docker:
      - image: cimg/php:8.0-browsers
    steps:
      - checkout
      - run:
          name: Install Composer
          command: |
            curl -s https://getcomposer.org/installer | php
            mv composer.phar /usr/local/bin/composer
      - run:
          name: Install production dependencies
          command: composer install --no-dev -o
      - persist_to_workspace:
          root: .
          paths:
            - vendor
  sync:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - d5:11:d7:d9:19:34:5f:79:31:25:e2:0d:6f:6d:65:a7
      - deploy:
          name: Deploy -built branch to github
          command: bash <(curl -s "https://raw.githubusercontent.com/Automattic/vip-go-build/master/deploy.sh")
workflows:
  test_build:
    jobs:
      - lint:
          filters:
            branches:
              ignore: /.*-built/
      - build:
          requires:
            - lint
          filters:
            branches:
              only: master
      - sync:
          requires:
            - build
          filters:
            branches:
              only: master